### ISSUE TITLE
Research table being used on a server freezes the client

### ISSUE THREAD

**Issue by iiDogez** [TheCodex6824/ThaumcraftFix#57]
When using the research table on a server, the client freezes and stops responding, not making a crash log.

The latest.log repeats the message below over and over again

 `[Client thread/ERROR]: SimpleChannelHandlerWrapper exception
java.lang.NullPointerException: null
	at net.minecraftforge.fml.common.network.FMLOutboundHandler$OutboundTarget$7.selectNetworks(FMLOutboundHandler.java:224) ~[FMLOutboundHandler$OutboundTarget$7.class:?]
	at net.minecraftforge.fml.common.network.FMLOutboundHandler.write(FMLOutboundHandler.java:378) ~[FMLOutboundHandler.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:111) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendToAllAround(SimpleNetworkWrapper.java:264) [SimpleNetworkWrapper.class:?]
	at thaumcraft.common.tiles.TileThaumcraft.sendMessageToClient(TileThaumcraft.java:33) [TileThaumcraft.class:?]
	at thaumcraft.common.tiles.TileThaumcraftInventory.syncSlots(TileThaumcraftInventory.java:134) [TileThaumcraftInventory.class:?]
	at thaumcraft.common.tiles.TileThaumcraftInventory.func_70299_a(TileThaumcraftInventory.java:91) [TileThaumcraftInventory.class:?]
	at net.minecraft.inventory.Slot.func_75215_d(Slot.java:70) [agr.class:?]
	at net.minecraft.inventory.Container.func_75141_a(Container.java:519) [afr.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.func_147266_a(NetHandlerPlayClient.java:1154) [brz.class:?]
	at net.minecraft.network.play.server.SPacketSetSlot.func_148833_a(SourceFile:30) [iu.class:?]
	at net.minecraft.network.play.server.SPacketSetSlot.func_148833_a(SourceFile:10) [iu.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_312]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_312]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1088) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_312]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_312]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_312]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_312]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]`
	
	1.12.2 forge version 14.23.5.2860 thaumcraft version 6.1BETA26

**Comment by TheCodex6824** [comment]
Is this a base Thaumcraft issue, or do you think it's caused by this mod? I've seen that in my logs before, but it never locked up my client before. If it can lag things to the point of freezing clients, then it's more serious than I thought.

**Comment by iiDogez** [comment]
This is purely a thaumcraft issue, I tested it with just thaumcraft installed

It doesnt even feel like lagging when it freezes, the game just stops with audio still in the background

**Comment by TheCodex6824** [comment]
This should be fixed in the latest version.
